/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const TransactionTransactionIdLazyRouteImport = createFileRoute(
  '/transaction/$transactionId',
)()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const TransactionTransactionIdLazyRoute =
  TransactionTransactionIdLazyRouteImport.update({
    id: '/transaction/$transactionId',
    path: '/transaction/$transactionId',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/transaction.$transactionId.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/transaction/$transactionId': typeof TransactionTransactionIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/transaction/$transactionId': typeof TransactionTransactionIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/transaction/$transactionId': typeof TransactionTransactionIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/transaction/$transactionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/transaction/$transactionId'
  id: '__root__' | '/' | '/transaction/$transactionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  TransactionTransactionIdLazyRoute: typeof TransactionTransactionIdLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/$transactionId': {
      id: '/transaction/$transactionId'
      path: '/transaction/$transactionId'
      fullPath: '/transaction/$transactionId'
      preLoaderRoute: typeof TransactionTransactionIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  TransactionTransactionIdLazyRoute: TransactionTransactionIdLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
